name: fast
description: An incredible command line interface for Flutter.
version: 0.6.0
homepage: https://github.com/dev-ideausher/fast.cli
# author: Pedro Bissonho <pedro.bissonho@gmail.com>

executables:
  fast:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3
  args: ^2.4.1
  logger: ^1.3.0
  process_run: ^0.13.0
  yaml: ^3.1.2
  http: ^0.13.6
  json2yaml: ^3.0.1
  pubspec_yaml: ^3.1.0
  plain_optional: ^1.0.0
  get: ^4.7.2
  get_storage: ^2.1.1
  dio: ^5.9.0
  google_fonts: ^4.0.4
  new_version_plus: ^0.0.10
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.7
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3

