name: fast
description: An incredible command line interface for Flutter.
version: 0.6.0
homepage: https://github.com/dev-ideausher/fast.cli
# author: Pedro Bissonho <pedro.bissonho@gmail.com>

executables:
  fast:

environment:
  sdk: ^3.10.0

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  logger: ^2.6.2
  process_run: ^1.2.4
  yaml: ^3.1.3
  http: ^1.6.0
  json2yaml: ^3.0.1
  pubspec_yaml: ^3.1.0
  plain_optional: ^1.0.0
  get: ^4.7.2
  get_storage: ^2.1.1
  dio: ^5.9.0
  google_fonts: ^6.3.2
  new_version_plus: ^0.1.1
  lottie: ^3.3.2
  flutter_svg: ^2.2.2
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.7
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

